### ISSUE TITLE
Character stats box [Dransik 2.0]

### ISSUE THREAD

**Issue by genkelvor** [IronWillGames/Dransik#115]
Armor is not calculating correctly the amount you suppose to have.

After you add your orbs the + check mark and x all stay in the box, not able to press them but should go away once out of orbs.
![image](https://user-images.githubusercontent.com/49921293/194667475-3a7f1bfc-6bfd-4836-b27a-0d1b061a7f99.png)

Where it shows your level on this box it's smushed together.
![image](https://user-images.githubusercontent.com/49921293/194668005-2a547cab-8d08-4904-a9be-a70108f1f47b.png)

**Comment by davidjreese** [comment]
fixed

**Comment by athacus** [comment]
@davidjreese It looks like the armor calculation is still not adding up. It is consistently showing as Armor: 10 even when I remove/add armor.
