### ISSUE TITLE
[Dransik 2.0] Dragging a stackable item from the ground onto another stack in backpack, causes duplicate on ground

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#126]
### [Dransik 2.0] Dragging a stackable item from the ground onto another stack in backpack, causes duplicate on ground

1. Log into a character
2. Ensure you have a stack of gold in your backpack
3. Find a monster that drops gold and kill it
4. Drag the gold from the ground into a stack of gold in your backpack
5. Notice that the gold creates a duplicated version on the ground. but it is also picked up

#### Expected:
When dragging a stackable item from the ground onto another stack in your backpack, it is removed from the ground.

#### Actual:
When dragging a stackable item from the ground onto another stack in your backpack, it causes a duplicate on the ground.

**Comment by davidjreese** [comment]
Think I fixed all cases of this visual artificat.

**Comment by athacus** [comment]
@davidjreese Looks like this issue is still occurring when you drag an item onto your character avatar, or if you drag the item into a stack of another in your backpack. The remaining "transparent" version of the item is still on the ground.

**Comment by davidjreese** [comment]
Reopened - issue now is the 'ghost stack' is on the ground still.

**Comment by davidjreese** [comment]
okay, think i have this
